export const ADD_COUNTRY = "ADD_COUNTRY";
export const REMOVE_COUNTRY = "REMOVE_COUNTRY";
export const UPDATE_COUNTRY = "UPDATE_COUNTRY";
export const SORT_COUNTRY = "SORT_COUNTRY";
export const FILTER_COUNTRY = "FILTER_COUNTRY";
